<a href="https://colab.research.google.com/github/techakilan/python-datascience-training/blob/master/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Import numpy

In [110]:
import numpy as np

# Create 1D array

In [111]:
onedarray = np.array([1])
print(onedarray)

[1]


In [112]:
onedarray2 = np.array([1,2,3])
print(onedarray2)

[1 2 3]


# Create 2d array

In [113]:
twodarray = np.array([[1]])
print(twodarray)

[[1]]


In [114]:
twodarray2 = np.array([[1,2],[3,4]])
print(twodarray2)

[[1 2]
 [3 4]]


# Create 3D array

In [115]:
threedarray = np.array([[[1]]])
print(threedarray)

[[[1]]]


In [116]:
threedarray2 = np.array([[[1,2,3],[7,8,9]],[[4,5,6],[9,8,7]], [[1,2,3],[7,8,9]],[[4,5,6],[9,8,7]]])
print(threedarray2)

[[[1 2 3]
  [7 8 9]]

 [[4 5 6]
  [9 8 7]]

 [[1 2 3]
  [7 8 9]]

 [[4 5 6]
  [9 8 7]]]


# Get dimension of an array

## Dimensions of 1D array

onedarray => 

[1]

The dimension of the array is 1

In [117]:
onedarray.ndim

1

onedarray2 => 

[1 2 3]

The dimension of the array is 1

In [118]:
onedarray2.ndim

1

## Dimension of 2D array

twodarray => 

[[1]]

The dimension of the array is 2

In [119]:
twodarray.ndim

2

twodarray2 => 

[[1 2]

 [3 4]]

 The dimension of the array is 2



In [120]:
twodarray2.ndim

2

## Dimension of 3D array

threedarray =>

[[[1]]]

The dimension of the array is 3

In [121]:
threedarray.ndim

3

threedarray2 =>

[[[1 2 3]
  [7 8 9]]

 [[4 5 6]
  [9 8 7]]

 [[1 2 3]
  [7 8 9]]

 [[4 5 6]
  [9 8 7]]]

The dimension of the array is 3

In [122]:
threedarray2.ndim

3

# Shape of array

## Shape of 1D array

onedarray =>

[[1]]

In [123]:
onedarray.shape

(1,)

The result (1, ) means the array has single index with a index length of 1. Total length of array is 1.

onedarray2 =>

[1 2 3]

In [124]:
onedarray2.shape

(3,)

The result (3,) means the array has single index with a index length of 3

i= 0    1    2

[  1    2     3]

The total length of array is 3

## Shape of 2D array

twodarray =>

[[1]]

In [125]:
twodarray.shape

(1, 1)

The result (1,1) means the array has 2 indexes (say i,j) and first index has length of 1 and second index has length of 1. The total length of array is 1.

i= 0

j= 0

[1]

twodarray2 =>

[[1 2]

 [3 4]]



In [126]:
twodarray2.shape

(2, 2)

The result (2,2) means that the array has 2 indexes(say i,j) and the first index has length of 2 and second index has length of 2. The total length of the array is 4.

i= 0    1

j= 0    1

[1 2 3 4]

In [131]:
twodarray2[1,1]

4

#Shape of 3D array

threedarray =>

[[[1]]]

In [128]:
threedarray.shape

(1, 1, 1)

The result means the array has 3 indexes(say i,j,k). The first index has length 1. Second index has length 1. Third index has length 1. The array length is 1

i = 0

j = 0

k = 0

[1]

threedarray2 =>


[[[1 2 3] [7 8 9]]

[[4 5 6] [9 8 7]]

[[1 2 3] [7 8 9]]

[[4 5 6] [9 8 7]]]

In [129]:
threedarray2.shape

(4, 2, 3)

The result means the array has 3 indexes(say i,j,k). The first index has length 4. Second index has length 2. Third index has length 3. The array length is 24.


i = 0    1    2    3

j = 0    1

k = 0    1    2

[1 2 3 7 8 9 4 5 6 9 8 7 1 2 3 7 8 9 4 5 6 9 8 7]

In [150]:
threedarray2[3,1,2]

7