<a href="https://colab.research.google.com/github/techakilan/python-datascience-training/blob/master/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Import numpy

In [1]:
import numpy as np

# Create 1D array

In [2]:
onedarray = np.array([1])
print(onedarray)

[1]


In [3]:
onedarray2 = np.array([1,2,3])
print(onedarray2)

[1 2 3]


# Create 2d array

In [4]:
twodarray = np.array([[1]])
print(twodarray)

[[1]]


In [5]:
twodarray2 = np.array([[1,2],[3,4]])
print(twodarray2)

[[1 2]
 [3 4]]


# Create 3D array

In [6]:
threedarray = np.array([[[1]]])
print(threedarray)

[[[1]]]


In [7]:
threedarray2 = np.array([[[1,2,3],[7,8,9]],[[4,5,6],[9,8,7]], [[1,2,3],[7,8,9]],[[4,5,6],[9,8,7]]])
print(threedarray2)

[[[1 2 3]
  [7 8 9]]

 [[4 5 6]
  [9 8 7]]

 [[1 2 3]
  [7 8 9]]

 [[4 5 6]
  [9 8 7]]]


# Get dimension of an array

### Dimensions of 1D array

onedarray => 

[1]

The dimension of the array is 1

In [8]:
onedarray.ndim

1

onedarray2 => 

[1 2 3]

The dimension of the array is 1

In [9]:
onedarray2.ndim

1

### Dimension of 2D array

twodarray => 

[[1]]

The dimension of the array is 2

In [10]:
twodarray.ndim

2

twodarray2 => 

[[1 2]

 [3 4]]

 The dimension of the array is 2



In [11]:
twodarray2.ndim

2

### Dimension of 3D array

threedarray =>

[[[1]]]

The dimension of the array is 3

In [12]:
threedarray.ndim

3

threedarray2 =>

[[[1 2 3]
  [7 8 9]]

 [[4 5 6]
  [9 8 7]]

 [[1 2 3]
  [7 8 9]]

 [[4 5 6]
  [9 8 7]]]

The dimension of the array is 3

In [13]:
threedarray2.ndim

3

# Shape of array

### Shape of 1D array

onedarray =>

[[1]]

In [14]:
onedarray.shape

(1,)

The result (1, ) means the array has single index with a index length of 1. Total length of array is 1.

onedarray2 =>

[1 2 3]

In [15]:
onedarray2.shape

(3,)

The result (3,) means the array has single index with a index length of 3

i= 0    1    2

[  1    2     3]

The total length of array is 3

### Shape of 2D array

twodarray =>

[[1]]

In [16]:
twodarray.shape

(1, 1)

The result (1,1) means the array has 2 indexes (say i,j) and first index has length of 1 and second index has length of 1. The total length of array is 1.

i= 0

j= 0

[1]

twodarray2 =>

[[1 2]

 [3 4]]



In [17]:
twodarray2.shape

(2, 2)

The result (2,2) means that the array has 2 indexes(say i,j) and the first index has length of 2 and second index has length of 2. The total length of the array is 4.

i= 0    1

j= 0    1

[1 2 3 4]

In [18]:
twodarray2[1,1]

4

### Shape of 3D array

threedarray =>

[[[1]]]

In [19]:
threedarray.shape

(1, 1, 1)

The result means the array has 3 indexes(say i,j,k). The first index has length 1. Second index has length 1. Third index has length 1. The array length is 1

i = 0

j = 0

k = 0

[1]

threedarray2 =>


[[[1 2 3] [7 8 9]]

[[4 5 6] [9 8 7]]

[[1 2 3] [7 8 9]]

[[4 5 6] [9 8 7]]]

In [20]:
threedarray2.shape

(4, 2, 3)

The result means the array has 3 indexes(say i,j,k). The first index has length 4. Second index has length 2. Third index has length 3. The array length is 24.


i = 0    1    2    3

j = 0    1

k = 0    1    2

[1 2 3 7 8 9 4 5 6 9 8 7 1 2 3 7 8 9 4 5 6 9 8 7]

In [21]:
threedarray2[3,1,2]

7

# Reshape an array

In [22]:
origarray = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15, 16])
print(origarray)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]


In [23]:
origarray.shape

(16,)

The result say this is one dimensional array, so it has single index. The length of the index is same as length of the array. the length is 16.

### Convert the array to two dimensional array of shape (2,8)

In [24]:
reshape2darray = origarray.reshape((2,8))
print(reshape2darray)

[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]]


In [25]:
reshape2darray.ndim

2

In [26]:
reshape2darray.shape

(2, 8)

### Convert the array to three dimensional array of shape (4,2,2)

In [27]:
reshape3darray = origarray.reshape((4,2,2))
print(reshape3darray)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]

 [[13 14]
  [15 16]]]


In [28]:
reshape3darray.ndim

3

In [29]:
reshape3darray.shape

(4, 2, 2)

# Array create methods

###  Create from list


In [40]:
arrayfromlist = np.array([1,2,3,4,5])
print(arrayfromlist)

[1 2 3 4 5]


### Create array having all values as zeroe 

In [42]:
array1dallzeros = np.zeros(10)
print(array1dallzeros)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [44]:
array2dallzeros = np.zeros((5,5))
print(array2dallzeros)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [46]:
array3dallzeros = np.zeros((2,3,4))
print(array3dallzeros)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


Another numpy function similar to numpy.zeros is numpy.ones. Instead of zeros all values are 1. 

In [48]:
arrayallones = np.ones((2,3))
print(arrayallones)

[[1. 1. 1.]
 [1. 1. 1.]]


In [37]:
X = np.arange(8).reshape(4,2)
print(X)

[[0 1]
 [2 3]
 [4 5]
 [6 7]]


In [38]:
X.sum(axis=1)

array([ 1,  5,  9, 13])