<a href="https://colab.research.google.com/github/techakilan/python-datascience-training/blob/master/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Import numpy

In [2]:
import numpy as np

# Create 1D array

In [3]:
onedarray = np.array([1])
print(onedarray)

[1]


In [4]:
onedarray2 = np.array([1,2,3])
print(onedarray2)

[1 2 3]


# Create 2d array

In [5]:
twodarray = np.array([[1]])
print(twodarray)

[[1]]


In [6]:
twodarray2 = np.array([[1,2],[3,4]])
print(twodarray2)

[[1 2]
 [3 4]]


# Create 3D array

In [7]:
threedarray = np.array([[[1]]])
print(threedarray)

[[[1]]]


In [8]:
threedarray2 = np.array([[[1,2,3],[7,8,9]],[[4,5,6],[9,8,7]], [[1,2,3],[7,8,9]],[[4,5,6],[9,8,7]]])
print(threedarray2)

[[[1 2 3]
  [7 8 9]]

 [[4 5 6]
  [9 8 7]]

 [[1 2 3]
  [7 8 9]]

 [[4 5 6]
  [9 8 7]]]


# Get dimension of an array

## Dimensions of 1D array

[1]

In [9]:
onedarray.ndim

1

[1 2 3]

In [10]:
onedarray2.ndim

1

## Dimension of 2D array

[[1]]

In [11]:
twodarray.ndim

2

[[1 2]

 [3 4]]



In [12]:
twodarray2.ndim

2

## Dimension of 3D array

In [13]:

threedarray.ndim

3

In [14]:
threedarray2.ndim

3

# Shape of array

## Shape of 1D array

[[1]]

In [19]:
onedarray.shape

(1,)

[1 2 3]

In [20]:
onedarray2.shape

(3,)

## Shape of 2D array

[[1]]

In [21]:
twodarray.shape

(1, 1)

[[1 2]

 [3 4]]



In [22]:
twodarray2.shape

(2, 2)