<a href="https://colab.research.google.com/github/techakilan/python-datascience-training/blob/master/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Import numpy

In [16]:
import numpy as np

# Create 1D array

In [17]:
onedarray = np.array([1])
print(onedarray)

[1]


In [23]:
onedarray2 = np.array([1,2,3])
print(onedarray2)

[1 2 3]


# Create 2d array

In [19]:
twodarray = np.array([[1]])
print(twodarray)

[[1]]


In [26]:
twodarray2 = np.array([[1,2],[3,4]])
print(twodarray2)

[[1 2]
 [3 4]]


# Create 3D array

In [21]:
threedarray = np.array([[[1]]])
print(threedarray)

[[[1]]]


In [31]:
threedarray2 = np.array([[[1,2,3],[7,8,9]],[[4,5,6],[9,8,7]], [[1,2,3],[7,8,9]],[[4,5,6],[9,8,7]]])
print(threedarray2)

[[[1 2 3]
  [7 8 9]]

 [[4 5 6]
  [9 8 7]]

 [[1 2 3]
  [7 8 9]]

 [[4 5 6]
  [9 8 7]]]


# Get dimension of an array

## Dimensions of 1D array

In [10]:
onedarray.ndim

1

In [34]:
onedarray2.ndim

1

## Dimension of 2D array

In [11]:
twodarray.ndim

2

In [33]:
twodarray2.ndim

2

## Dimension of 3D array

In [14]:

threedarray.ndim

3

In [32]:
threedarray2.ndim

3