<a href="https://colab.research.google.com/github/techakilan/python-datascience-training/blob/master/PythonNumpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Import numpy

Lists cons - 
* Take up lot of memory
* Performance issue
* Lacks functionality

In [36]:
import numpy as np

# Create 1D array

#### Every element is a scalar

In [ ]:
onedarray = np.array([1])
print(onedarray)

[1]


In [ ]:
onedarray2 = np.array([1,2,3])
print(onedarray2)

[1 2 3]


# Create 2d array

#### can be considered as 1D array having every element as 1D array

In [ ]:
twodarray = np.array([[1]])
print(twodarray)

[[1]]


In [ ]:
twodarray2 = np.array([[1,2],[3,4]])
print(twodarray2)

[[1 2]
 [3 4]]


In [ ]:
one1 = np.array([1,2,3])
one2 = np.array([3,4,5])
two1 = np.array([one1,one2])
two1

array([[1, 2, 3],
       [3, 4, 5]])

# Create 3D array
#### can be considered as 1D array where every element is a 2D array

In [ ]:
threedarray = np.array([[[1]]])
print(threedarray)

[[[1]]]


In [ ]:
threedarray2 = np.array([[[1,2,3],[7,8,9]],[[4,5,6],[9,8,7]], [[1,2,3],[7,8,9]],[[4,5,6],[9,8,7]]])
print(threedarray2)

[[[1 2 3]
  [7 8 9]]

 [[4 5 6]
  [9 8 7]]

 [[1 2 3]
  [7 8 9]]

 [[4 5 6]
  [9 8 7]]]



[
 
  1 2
 
  3 4
  
  ]

In [ ]:
np.array([[1,2],[3,4]])

array([[1, 2],
       [3, 4]])

# Get dimension of an array

### Dimensions of 1D array

onedarray => 

[1]

The dimension of the array is 1

In [ ]:
print(onedarray)

[1]


In [ ]:
onedarray.ndim

1

onedarray2 => 

[1 2 3]

The dimension of the array is 1

In [ ]:
onedarray2.ndim

1

### Dimension of 2D array

twodarray => 

[[1]]

The dimension of the array is 2

In [ ]:
twodarray.ndim

2

twodarray2 => 

[[1 2]

 [3 4]]

 The dimension of the array is 2



In [ ]:
twodarray2.ndim

2

### Dimension of 3D array

threedarray =>

[[[1]]]

The dimension of the array is 3

In [ ]:
threedarray.ndim

3

threedarray2 =>

[[[1 2 3]
  [7 8 9]]

 [[4 5 6]
  [9 8 7]]

 [[1 2 3]
  [7 8 9]]

 [[4 5 6]
  [9 8 7]]]

The dimension of the array is 3

In [ ]:
threedarray2.ndim

3

# Shape of array

### Shape of 1D array

onedarray =>

[1]

In [ ]:
onedarray.shape

(1,)

The result (1, ) means the array has single index with a index length of 1. Total length of array is 1.

onedarray2 =>

[1 2 3]

In [ ]:
onedarray2.shape

(3,)

The result (3,) means the array has single index with a index length of 3

i= 0    1    2

[  1    2     3]

The total length of array is 3

### Shape of 2D array

twodarray =>

[[1]]

In [ ]:
twodarray.shape

(1, 1)

The result (1,1) means the array has 2 indexes (say i,j) and first index has length of 1 and second index has length of 1. The total length of array is 1.

i= 0

j= 0

[1]

twodarray2 =>

[[1 2]

 [3 4]]



In [ ]:
twodarray2.shape

(2, 2)

The result (2,2) means that the array has 2 indexes(say i,j) and the first index has length of 2 and second index has length of 2. The total length of the array is 4.

i= 0    1

j= 0    1

[1 2 3 4]

In [ ]:
myarr = np.array([ [1,2,3],[4,5,6]])
print(myarr)

[[1 2 3]
 [4 5 6]]


In [ ]:
myarr[1][2]

6

In [ ]:
myarr.ndim

2

In [ ]:
myarr.shape

(2, 3)

### Shape of 3D array

threedarray =>

[[[1]]]

In [ ]:
threedarray.shape

(1, 1, 1)

The result means the array has 3 indexes(say i,j,k). The first index has length 1. Second index has length 1. Third index has length 1. The array length is 1

i = 0

j = 0

k = 0

[1]

threedarray2 =>


[[[1 2 3] [7 8 9]]

[[4 5 6] [9 8 7]]

[[1 2 3] [7 8 9]]

[[4 5 6] [9 8 7]]]

In [ ]:
threedarray2.shape

(4, 2, 3)

The result means the array has 3 indexes(say i,j,k). The first index has length 4. Second index has length 2. Third index has length 3. The array length is 24.


i = 0    1    2    3

j = 0    1

k = 0    1    2

[1 2 3 7 8 9 4 5 6 9 8 7 1 2 3 7 8 9 4 5 6 9 8 7]

In [ ]:
threedarray2[3,1,2]

7

The result seven means at the index [3,1,2] we find the element 7

# Reshape an array

In [ ]:
origarray = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15, 16])
print(origarray)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]


In [ ]:
origarray.shape

(16,)

The result say this is one dimensional array, so it has single index. The length of the index is same as length of the array. the length is 16.

### Convert the array to two dimensional array of shape (2,8)

In [ ]:
reshape2darray = origarray.reshape((2,8))
print(reshape2darray)

[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]]


In [ ]:
newarr = origarray.reshape((8,2))
newarr

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12],
       [13, 14],
       [15, 16]])

In [ ]:
newarr.shape

(8, 2)

In [ ]:
reshape2darray.ndim

2

In [ ]:
reshape2darray.shape

(2, 8)

### Convert the array to three dimensional array of shape (4,2,2)

In [ ]:
reshape3darray = origarray.reshape((4,2,2))
print(reshape3darray)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]

 [[13 14]
  [15 16]]]


In [ ]:
reshape3darray.ndim

3

In [ ]:
reshape3darray.shape

(4, 2, 2)

In [ ]:
reshape3darray.reshape((16,))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

# Array create methods

###  Create from list


In [ ]:
arrayfromlist = np.array([1,2,3,4,5])
print(arrayfromlist)

[1 2 3 4 5]


In [ ]:
type(arrayfromlist)

numpy.ndarray

### Create array having all values as zeroe 

In [ ]:
array1dallzeros = np.zeros(10)
print(array1dallzeros)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [ ]:
array2dallzeros = np.zeros((5,5))
print(array2dallzeros)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [ ]:
array3dallzeros = np.zeros((2,3,4))
print(array3dallzeros)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


Another numpy function similar to numpy.zeros is numpy.ones. Instead of zeros all values are 1. 

In [ ]:
arrayallones = np.ones((2,3))
print(arrayallones)

[[1. 1. 1.]
 [1. 1. 1.]]


### Create array having all random values

In [ ]:
arrayallrandom = np.random.random((2,3))
print(arrayallrandom)

[[0.02575559 0.16799989 0.23139095]
 [0.90956997 0.99700506 0.92750267]]


### Create array having all values with normal distribution

In [ ]:
arrayallrandomnormal =  np.random.randn(10)
print(arrayallrandomnormal)

[-0.78704292 -0.3068476   0.34616153 -1.5117913   0.08522278  1.48084703
  0.68632777 -0.19729026  0.9181675   0.17126893]


In [ ]:
array2dallrandomnormal = arrayallrandomnormal.reshape((2,5))
print(array2dallrandomnormal)

[[-0.78704292 -0.3068476   0.34616153 -1.5117913   0.08522278]
 [ 1.48084703  0.68632777 -0.19729026  0.9181675   0.17126893]]


### Create equally spaced (linearly spaced) array

In [ ]:
arraylinspaced = np.linspace(0,10,5)
print(arraylinspaced)

[ 0.   2.5  5.   7.5 10. ]


### Create equally spaced(taking space as input) array

In [ ]:
arrayarange = np.arange(0,10,2.5)
print(arrayarange)

[0.  2.5 5.  7.5]


# Array operations

Numpy arrays operate differently compared to python lists as numpy arrays allow large number of mathematical operation to be performed on them. As mentioned earlier, they are also superfast.

### Scalar operations

In [ ]:
cardsarray = np.array([1,2,3,4,5])
print(cardsarray)

In [ ]:
# Multiply cardsarray with scalar value of 5
scalarmulcardsarray = 5*cardsarray
print(scalarmulcardsarray)

In [ ]:
#Divide cards array with scalar value of 5
cardsarraydivscalar = cardsarray/5
print(cardsarraydivscalar) 

In [ ]:
#Reciprocal of cardsarray values
reciprocalcardsarray = 1/cardsarray
print(reciprocalcardsarray)

### Conditional Operations

In [ ]:
conditionalarray = np.array([1,2,3,4,5,6,7,8,9])
print(conditionalarray) 

In [ ]:
conditionalarray > 5

In [ ]:
conditionalarray < 5

In [ ]:
conditionalarray == 5

#### use conditional as index

In [ ]:
conditionalarray[conditionalarray>3]

### Apply user defined function on all elements on an array

In [ ]:
ufarray = np.array([1,2,3,4,5])
print(ufarray)

In [ ]:
def f(x):
  return x**x+1

In [ ]:
f(2)

In [ ]:
f(ufarray)

### Matrix Multiplcation using array

Create two simple 2D matrices matrixA and MatrixB. matrixA has shape (1,3) and matrixB has shape (3,1)

In [ ]:
matrixA = np.array([[1,2,3]])
print(matrixA)

In [ ]:
matrixA.shape

In [ ]:
matrixB = np.array([[1],[2],[3]])
print(matrixB)

In [ ]:
matrixB.shape

### dot product of matrices

In [ ]:
dotProd = matrixA.dot(matrixB)
print(dotProd)

In [ ]:
matrixA.ndim

In [ ]:
matrixB.ndim

In [ ]:
dotProd.ndim

In [ ]:
#### Another way to achieve dot product
print(matrixA@matrixB)

### Matrix multiplication


[[1 2 3]] * [
  
  [1]
 [2]
 [3]
 
 ]


In [ ]:
matrixA*matrixB

In [ ]:
a=np.array([1,2,3])
b=np.array([3,2,1])
a*b

# Simple plots using plyplot

### line plot

In [ ]:
import matplotlib.pyplot as plt

In [ ]:
x= np.random.randn(10)
plt.hist(x)

In [ ]:
x=np.array([1,2,3,4,5,6,7])
plt.plot(x, x**x)

# Array indexing

## Index 1D array

In [ ]:
index1d =np.array([1,2,3,4,5])
print(index1d)

In [ ]:
### First Element
index1d[0]

In [ ]:
### Last Element
index1d[4]

## Index 2D array

In [ ]:
index2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(index2d)

#### To get first 1D array

In [ ]:
index2d[0]

In [ ]:
###First Element
index2d[0,0]

In [ ]:
###Last Element
index2d[2,2]

In [ ]:
### central element
index2d[1,1]

### Index 3D array

In [ ]:
index3d = np.array([ [[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]],[[13,14,15],[16,17,18]] ])
print(index3d)

#### To get first 2D array

In [ ]:
index3d[0]

#### To get first 1D array from first 2D array

In [ ]:
index3d[0,0]

#### To get the first element

In [ ]:
index3d[0,0,0]

# Array Slicing
##[start:end:step]

### default value for start =0

### default value for end = length of the array

### default value for step = 1

### Slice 1D array

In [ ]:
slice1d =np.array([1,2,3,4,5])
print(slice1d)

In [ ]:
### Get First 2 elements. expected values for [start:end:step] =>[0:2:1]

### [0:2:1]
print("pattern => [0:2:1]")
print(slice1d[0:2:1])
print("--------------")
### same as [:2]
print("pattern =>[:2]")
print(slice1d[:2])




In [ ]:
### Exclude first 2 elements. expected values for [start:end:step] =>[0:2:1]

### same as [2:5:1]
print("pattern [2:5:1]")
print(slice1d[2:5:1])
print("--------------")
### same as [2:]
print("pattern [2:]")
print(slice1d[2:])





In [ ]:
### Get last two elements. expected values for [start:end:step] =>[3:5:1] or [-2:5:1] or [-2:]
print("pattern [3:5:1]")
print(slice1d[3:5:1])
print("--------------")
print("pattern [-2:5:1]")
print(slice1d[-2:5:1])
print("--------------")
print("pattern [-2:]")
print(slice1d[-2:])

In [ ]:
### Exclude last two elements  expected values for [start:end:step] =>[0:3:1] or [0:-2:1] or [:-2]
print("pattern [0:3:1]")
print(slice1d[0:3:1])
print("--------------")
print("pattern [0:-2:1]")
print(slice1d[0:-2:1])
print("--------------")
print("pattern [:-2]")
print(slice1d[:-2])

#### Use conditional array for slicing

In [ ]:
### Check indexes where value is greater than 2
conditionalindexes = slice1d>2
print(conditionalindexes)

In [ ]:
### Use conditional index to values greater than 2

print(slice1d[conditionalindexes])

In [ ]:
### conditional slicing can be done directly on the array itself
print(slice1d[slice1d>2])

In [ ]:
### more conditional slicing
x=np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15])
print(x[x%3==0])

In [ ]:
### conditional using strings - Get all country name starting with i
countries = np.array(["argentina", "india","afghanisthan","england","israel","usa", "france","iran"])
### create an array of first letters of the countries 
first_letters = np.vectorize(lambda s: s[0]) (countries)
### use first letters as indexes
print(countries[first_letters=="i"])


In [ ]:
### Or the above conditional may be combined in single line
print(countries[np.vectorize(lambda s:s[0])(countries)=="i"])

### Slice 2D array

#### A 2D array is array with elements which are 1D array

In [ ]:
slice2d =  np.array([[1,2,3],[4,5,6],[7,8,9]])
print(slice2d)

In [ ]:
### Get the first 2 elements of the 2D array. Remember the elements of 2D array is 1D array
### expected values for [start:end:step] =>[0:2:1] or [:2]
print("pattern [0:2:1]")
print(slice2d[0:2:1])
print("--------------")
print("pattern [:2]")
print(slice2d[:2])


### Slice 3D array

A 3D array is array with elements which are 2D array

In [ ]:
slice3d = np.array([ [[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]],[[13,14,15],[16,17,18]] ])
print(slice3d)

In [ ]:
### Get the first 2 elements of the 3D array. Remember the elements of 3D array is 2D array
### expected values for [start:end:step] =>[0:2:1] or [:2]
print("pattern [0:2:1]")
print(slice3d[0:2:1])
print("--------------")
print("pattern [:2]")
print(slice3d[:2])

### Iterate through an array

##### 1d array

In [ ]:
import numpy as np

arr = np.array([1, 2, 3])

for x in arr:
  print(x) 

##### 2d array

In [ ]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  for y in x:
    print(y) 

##### 3d array

In [ ]:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in arr:
  for y in x:
    for z in y:
      print(z)

In [42]:
arr = np.array([[1,2,3],[4,5,6]])
for x in arr:
  for y in x:
   print("the value in the array is")
   print(y)
  print("out of child loop") 
print("out of parent loop")

the value in the array is
1
the value in the array is
2
the value in the array is
3
out of child loop
the value in the array is
4
the value in the array is
5
the value in the array is
6
out of child loop
out of parent loop


[1,2,3]
for:

1


##### iterating using nditer()

In [ ]:
import numpy as np

arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

for x in np.nditer(arr):
  print(x) 

### Dtype

In [ ]:
my_int = 1
type(my_int)


Whether i32 or i64 is used will depend on architecture of the host machine running the program

In [ ]:
print(np.dtype('i2'))
print(np.dtype('i4'))
print(np.dtype('i8'))

In [ ]:
arr = np.array([1, 2, 3, 4], dtype='S')

print(arr)
print(arr.dtype) 

In [ ]:
arr1 = np.array([1, 2, 3, 4])

print(type(arr1))
print(type(arr1[0])) 

In [ ]:
arr2 = np.array(arr1, dtype='i4')

print(type(arr2))
print(type(arr2[0])) 


### Enumerate

In [47]:
arr = np.array([1, 2, 3])
new_arr = np.ndenumerate(arr)

print(new_arr)

In [48]:
for i,x in new_arr:
  print("index is "+str(i)+" value is "+str(x))

index is (0,) value is 1
index is (1,) value is 2
index is (2,) value is 3


### Join

##### Simple

In [49]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.concatenate((arr1, arr2))

print(arr) 

[1 2 3 4 5 6]


###### 2d array

In [50]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

In [ ]:
arr1

array([[1, 2],
       [3, 4]])

In [ ]:
arr2

array([[5, 6],
       [7, 8]])

##### concatenate along rows

In [ ]:
joinedbyrow = np.concatenate((arr1, arr2), axis=1)
joinedbyrow

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

##### Concatenate along columns

default axis value is zero

In [51]:
joinedbycolumn=np.concatenate((arr1, arr2))
joinedbycolumn

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [52]:
print(arr1.ndim)
print(arr2.ndim)
print(joinedbyrow.ndim)
print(joinedbycolumn.ndim)

2
2
2
2


##### using stack

In [ ]:
arr1

array([[1, 2],
       [3, 4]])

In [ ]:
arr2

array([[5, 6],
       [7, 8]])

In [56]:
stackedbyrow = np.stack((arr1,arr2), axis=1)
stackedbyrow

array([[[1, 2],
        [5, 6]],

       [[3, 4],
        [7, 8]]])

In [57]:
stackedbycolumn=np.stack((arr1,arr2))
stackedbycolumn

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [ ]:
print(arr1.ndim)
print(arr2.ndim)
print(stackedbyrow.ndim)
print(stackedbycolumn.ndim)

2
2
3
3


##### using hstack

In [ ]:
arr1

array([[1, 2],
       [3, 4]])

In [ ]:
arr2

array([[5, 6],
       [7, 8]])

In [ ]:
# the hstack is same as concatenate with axis=1
np.hstack((arr1,arr2))

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

##### using vstack

In [ ]:
# the vstack is same as concatenate with axis=0
np.vstack((arr1,arr2))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

### Split

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6])
newarr = np.array_split(arr, 3)
print(newarr[0])
print(newarr[1])
print(newarr[2]) 

### Search

##### where() returns indexes

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 4, 4])
x = np.where(arr == 4)
print(x) 

In [ ]:
print(arr[x]) 

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
x = np.where(arr%2 == 0)
print(x)
print(arr[x])

### Sort

In [60]:
arr = np.array([3, 2, 0, 1])
print(np.sort(arr)) 

[0 1 2 3]


In [61]:
arr = np.array(['banana', 'cherry', 'apple'])
print(np.sort(arr)) 

['apple' 'banana' 'cherry']


### Filter

In [62]:
arr = np.array([41, 42, 43, 44])
x = [True, False, True, False]
newarr = arr[x]
print(newarr) 

[41 43]


### Miscellaneous

In [ ]:
simple3darray = np.arange(20).reshape(2,5,2)
simple3darray

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]]])

##### Collapse an axis along a axis=0

In [ ]:
np.sum(simple3darray, axis=0)

array([[10, 12],
       [14, 16],
       [18, 20],
       [22, 24],
       [26, 28]])

##### Collapse an axis along axis=1

In [ ]:
np.sum(simple3darray, axis=1)

array([[20, 25],
       [70, 75]])

##### Collapse an axis along axis=2

In [ ]:
np.sum(simple3darray, axis=2)

array([[ 1,  5,  9, 13, 17],
       [21, 25, 29, 33, 37]])

##### Progressively collapse an array to get a single scalar value

In [ ]:
c1 = np.sum(simple3darray,axis=0)
c1

array([[10, 12],
       [14, 16],
       [18, 20],
       [22, 24],
       [26, 28]])

In [ ]:
c2 = np.sum(c1,axis=0)
c2

array([ 90, 100])

In [ ]:
c3 = np.sum(c2,axis=0)
c3

190

In [ ]:
np.sum(simple3darray)

190